### ISSUE TITLE
Filter/Search

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-server#225]
I think that we may want to revisit the way that our filter is working.  Perhaps we want to make it more like a search?  I don't think it's obvious that the filter is only working on the 50 posts that are being displayed.  Additionally, I think the addition of the filter has slowed the interface down.

I am proposing that the same interface for 'filtering' exists, however it is actually adjusting what is being sent to the admin/get_posts.json as paramters.  This would make the interface 'less bogged down', would make the results more intuitive, and would close #189.

@Nolski all feedback welcome.

**Comment by Nolski** [comment]
I agree. I think with time and further discussion we would want to add additional filters such as approved posts. I don't really love the current drop down method of doing things since it makes it difficult to combine filters so for instance, I might want to obtain all posts which have images OR text and are approved.

**Comment by thequbit** [comment]
I think we should remove all masonry filtering ( already done on new server ), and just make this full-text search ( which is supported by Postgresql, which we are using ).  Closing this since I think we should focus on just full database search next, not just the items that are currently in view.
