### ISSUE TITLE
500 On get_posts.json with image posts

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#43]
Looks like a bad day today backend wise.

So I'm getting a 500 when one of my posts has an image in it. It looks like you're trying to use `splitext` which isn't ever defined. I think you want it to be `os.path.splitext`.

This is at:
https://github.com/hhroc/yellr-server/blob/master/yellr-serv%2Fyellrserv%2Fadmin_views.py#L247

This sort of error could have been easily caught by a basic linter such as [flake8](https://pypi.python.org/pypi/flake8) which I think might be a good idea to start using.

**Comment by thequbit** [comment]
Caught this as well.  Didn't see it before because the tests didn't upload an image.  Fixed in the latest commit to my repo.

https://github.com/thequbit/yellr-server/blob/1c56e920ee8701b79e87e54ad5d07c22bf2ef584/yellr-serv/yellrserv/admin_views.py#L247

( i also fixed it in the other places and the tests pass).

I am not familiar with flake8, I'll need to take some time to look into that.  Thanks for pointing me to it.

**Comment by Nolski** [comment]
lets keep this open until it's merged into hhroc's repo so I don't actually merge breaking changes.

**Comment by thequbit** [comment]
Makes sense.   Thanks.

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by Nolski** [comment]
This PR resolves this: https://github.com/hhroc/yellr-server/pull/48
