### ISSUE TITLE
[Mod-Site] Multiple Login Bug

### ISSUE THREAD

**Issue by reustonium** [hhroc/yellr-server#90]
If I login as `system` I can see items in the raw feed, assignments, etc.

When somebody else logs in with the same account on a different browser/device/ip(?), my session remains logged in however I can no longer see any items (including raw feed, stories, assignments, etc).

This behavior has repeated several times in the last few days.

**Comment by thequbit** [comment]
Yup, known bug.  Right now we only allow a user to be logged in in a single location at a time.  The front-end does not handle this well.  It should be kicking you out to a login page, however it just kind of crashes.

I believe this may be because not all of the end-points are wrapped in try/except blocks for debugging.  I'll try wrapping them all up, and test again.

**Comment by thequbit** [comment]
@Nolski although not the worst thing that we need to hit the logout button when this happens, we should investigate what is actually going on.  Can we make the default screen the login screen rather than the raw feed screen, so it 'fails gracefully' when our token is bad?

Note this also could be related to #29

**Comment by thequbit** [comment]
@Nolski we need to elevate this I think.  It shouldn't be too bad once we deploy, but it is killer in development mode ...

Let me know if you think it's a quick fix or not.  I would think that just looking at the success field should be enough to say 'okay, let's just bring them back to the login screen'.

**Comment by Nolski** [comment]
I think instead of continuing to create hacks around this issue we should just store the user's login credentials as a session cookie which in turn creates a more secure website and causes less headaches

**Comment by thequbit** [comment]
Token being kept in session has been implemented.

**Comment by thequbit** [comment]
Closing, since this, I believe, has been fixed with the latest and greatest from @Nolski with the session migration.  @reustonium feel free to re-open if the bug shows up again.
